FROM python:3.8.10-slim AS builder

WORKDIR /opt/dagster/app

COPY . .

RUN mkdir -p /opt/dagster/app/processed_data /opt/dagster/app/archived_data

RUN pip install --no-cache-dir dagster dagster-postgres dagster-docker -r requirements.txt

FROM python:3.8.10-slim

COPY --from=builder /usr/local/bin/dagster /usr/local/bin/dagster

WORKDIR /opt/dagster/app

COPY --from=builder /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
COPY --from=builder /opt/dagster/app/ /opt/dagster/app/

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repo.py"]
