# local development
version: '3'

x-common-service-config: &common-service-config
  restart: unless-stopped

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "49000:9000"
      - "49001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1234567890
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: *common-service-config


  etl:
    container_name: etl
    build:
      context: .
      dockerfile: ./src/Dockerfile
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/health" ]  # Replace with the actual health check endpoint
      interval: 30s
      timeout: 10s
      retries: 3
    command: bash -c "while true; do python src/main.py; sleep 60; done"
    <<: *common-service-config

volumes:
  minio_storage: {}