FROM python:3.8-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

# Add repository code
WORKDIR /opt/dagster/app

COPY .env /opt/dagster/app
COPY requirements.txt /opt/dagster/app
COPY customer_etl.py transactions_etl.py products_etl.py erasure_requests_etl.py common.py /opt/dagster/app/
COPY customer_schema.json transactions_schema.json products_schema.json erasure_requests_schema.json /opt/dagster/app/

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org --no-cache-dir -r requirements.txt

COPY repo.py erasure_requests.py customers.py transactions.py products.py /opt/dagster/app/

COPY raw_data /opt/dagster/app/raw_data
COPY processed_data /opt/dagster/app/processed_data
COPY archived_data /opt/dagster/app/archived_data
# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repo.py"]
